# Startup:
# ```
# CROMWELL_TAG=develop
# docker-compose -f scripts/docker-compose-mysql/docker-compose-horicromtal.yml up --scale cromwell=3
# ```

# Cleanup:
# ```
# docker-compose -f scripts/docker-compose-mysql/docker-compose-horicromtal.yml down -v && rm -r scripts/docker-compose-mysql/cromwell-executions
# ```
version: '2.3'
services:
  cromwell_lord:
    image: "broadinstitute/cromwell:${CROMWELL_TAG}"
    network_mode: host
    working_dir: /cromwell-working-dir
    volumes:
      - ./cromwell-executions:/cromwell-working-dir/cromwell-executions
      - ./compose/cromwell/app-config:/app-config
    command: ["server"]
    environment:
      - JAVA_OPTS=-Dconfig.file=/app-config/test-horicromtal.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 2s
      timeout: 30s
      retries: 60
    ports:
      - 8000:8000
  cromwell_soldier:
    image: "broadinstitute/cromwell:${CROMWELL_TAG}"
    working_dir: /cromwell-working-dir
    volumes:
      - ./cromwell-executions:/cromwell-working-dir/cromwell-executions
      - ./compose/cromwell/app-config:/app-config
    depends_on:
      cromwell_lord:
        condition: service_healthy
    command: ["server"]
    environment:
      - JAVA_OPTS=-Dconfig.file=/app-config/test-horicromtal-soldier.conf
    ports:
      - 8001:8000
